### ISSUE TITLE
Console client gets stuck on sending messages to whisper proto layer

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-console-client#50] opened 2019-05-24 10:46 UTC
To reproduce sent multiple messages. Around 5-10 client will be stuck

**Comment by adambabik** [comment] 2019-05-27 10:02
I can't send even one so it's a regression. Will assign to myself because it's the same root cause as in #58.

**Comment by dshulyak** [comment] 2019-05-27 10:17
btw i can't make it hang with updated status-go https://github.com/status-im/status-console-client/pull/49 . i fixed one issue with hanged history retrieval. maybe it has effect on some other parts as well

**Comment by dshulyak** [comment] 2019-05-27 11:20
yeah i think it is fixed with status-go update. there was an issue where one of the whisper feed subscribers wasn't consuming events from feed. and thus all publishers hanged. because each whisper processQueue publishes to feed - they all got stuck. and whisper.Send got stuck as well because it tries to send to the channel that should be consumed by whisper.processQueue.

**Comment by dshulyak** [comment] 2019-05-27 11:23
@adambabik i merged status-go update. can you retest this issue please?

**Comment by adambabik** [comment] 2019-05-27 11:54
@dshulyak just pulled master and it seems like the problem is fixed.

**Closed** 2019-05-29 21:33 UTC
